#:schema node_modules/wrangler/config-schema.json
name = "chronosky"
main = "src/cron.ts"
compatibility_date = "2024-04-19"

# Cron Triggers
[triggers]
crons = ["* * * * *"] # * * * * * = run every minute

# KV Namespaces
[[kv_namespaces]]
binding = "KV_ACCOUNTS"
id = ""

